nodejs/next-10

meetings/2020-07-29.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
=> doc: add minutes for meeting 29 Jul 2020

meetings/2020-07-15.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
=> doc: add minutes from first post-summit meeting

meetings/2020-08-12.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
=> doc: add minutes for meeting 12 Aug 2020

meetings/2020-09-02.md
Signed-off-by: Michael Dawson <michael_dawson@ca.ibm.com>
=> doc: add minutes for meeting 2 Sep 2020

meetings/2020-09-17.md
=> doc: add minutes for meeting 17 Sep 2020

CONSTITUENCIES.md
=> Add "Organizations" to `CONSTITUENCIES.md`

README.md
=> Add iansu to members list

meetings/2020-10-01.md
=> doc: add minutes for meeting 1 oct 2020

meetings/2020-10-28.md
=> doc: minutes for meeting 28 oct 2020

meetings/2020-11-12.md
=> doc: add minutes for meeting 12 Nov 2020

CONSTITUENCY-NEEDS.md
Capture/organize the output from team discussions
on needs.
Refs: https://github.com/nodejs/next-10/issues/20
=> doc: initial cut at constituencies needs

CONSTITUENCY-NEEDS.md
=> fix: alignment of needs matrix

meetings/2021-01-06.md
=> doc: add minutes for meeting 6 Jan 2021

meetings/2021-01-21.md
=> doc: add minutes for meeting 21 Jan 2021

meetings/2021-02-04.md
=> doc: add minutes for meeting 4 Feb 2021

meetings/2021-02-11.md
=> doc: add minutes for meeting 11 Feb 2021

meetings/2021-03-25.md
=> doc: add minutes for meeting 25 March 2021

meetings/2021-04-08.md
=> doc: add minutes for meeting 8 April 2021

meetings/2021-05-10.md
=> doc: add minutes for meeting 10 May 2021

meetings/2021-06-07.md
=> doc: add minutes for meeting 7 Jun 2021

CONSTITUENCY-NEEDS.md
* Add additional needs based on team review of the
write in section of the survey
=> doc: add new constituency needs 

meetings/2021-07-12.md
=> doc: addminutes for 12 July 2021

meetings/2021-08-23.md
=> doc: add minutes for meeting Aug 23 2021

meetings/2021-09-27.md
=> doc: add minutes for meeting 27 Sep 2021

meetings/2021-10-27.md
=> doc: add minutes for meeting 27 Oct 2021

meetings/2021-11-10.md
=> doc: add minutes for meeting 10 Nov 2021

meetings/2021-12-08.md
=> doc: add minutes for meeting 8 Dec 2021

meetings/2022-01-19.md
=> doc: add minutes for meeting 19 Jan 2022

meetings/summit-jan-2022.md
=> doc: add minutes for mini-summit Jan 27 2022

meetings/2022-02-16.md
=> doc: add minutes for meeting 16 Feb 2022

meetings/2022-03-16.md
=> doc: add minutes for meeting 16 March 2022

meetings/2022-03-30.md
=> doc: add minutes for meeting 30 March 2022

meetings/2022-04-27.md
=> doc: add minutes for meeting 27 April 2022

meetings/summit-jun-2022.md
=> doc:  minutes for deep dives at Jun Collab summit

meetings/2022-07-06.md
=> doc: add minutes for meeting July 6 2022

TECHNICAL_PRIORITY_WORKING_SUMMARY.md
=> doc: add technical priorities working summary

meetings/2022-07-20.md
=> doc: add minutes for 20 Jul 2022

meetings/2022-09-07.md
=> doc: minutes for meeting 7 Sep 2022

meetings/2022-09-21.md
=> doc: add minutes for meeting 21 Sep 2022

meetings/2022-10-12.md
=> doc: add minutes for meeting 12 Oct 2022

meetings/2022-10-26.md
=> doc: add minutes for meeting 26 Oct 2022

collaborator summit/2022-dublin/community-brainstorm.md
add the second part of the easyretro we did during the collaborator summit in dublin. This one is focus on the community brainstorm which a comparaison of the results with the last survey
Linked to https://github.com/nodejs/next-10/issues/159
=> chore: result from the community brainstorm

README.md
@boneskull asked that I remove him.
=> Remove Chris

meetings/2022-11-23.md
=> doc: add minutes for meeting 23 Nov 2022

meetings/2023-01-04.md
=> doc: add minutes for meeting 4 Jan 2023

README.md
=> doc: move inactive members to Emeritus

meetings/2023-01-18.md
=> doc: add minutes for meeting 18 Jan 2023

meetings/2022-11-23.md
=> doc: fix link to issue

collaborator summit/2023-vancouver/community-brainstorm.md
https://easyretro.io/publicboard/uUlQgng4WngJPXjxLc0drc2BLEp1/fda90089-b531-41fc-8e2d-bfd7600d5309
=> feat: 2023 vancouver summit community

README.md
Adding myself (Amal Hussein) to list of Next 10 WG members cc @sheplu @mhdawson
=> Adding Amal Hussein to list of Next 10 WG members

README.md
I'd like to be in the member list
@nodejs/next-10
=> Add marco-ippolito to members

meetings/2024-04-17.md
Fixes: https://github.com/nodejs/next-10/issues/264
@nodejs/next-10
=> chore: add minutes for 2024-04-17 meeting

README.md
Ref: https://github.com/nodejs/next-10/pull/276#issuecomment-2158065956
=> Add @UlisesGascon to the team

.gitignore, surveys/2024-09/questions.md
Refs: https://github.com/nodejs/next-10/issues/271
@nodejs/next-10 PTAL
My plan is to go out with the survey on monday 9th September
=> feat: add survey for healthy collaborator base
